'use client'

import { useState, useEffect } from 'react'

interface CurrencyConversion {
  from: string
  to: string
  amount: number
  convertedAmount: number
  rate: number
  timestamp: string
  source: string
}

interface CurrencyHook {
  convertCurrency: (from: string, to: string, amount: number, country?: string) => Promise<CurrencyConversion>
  convertByCountry: (from: string, amount: number, country: string) => Promise<CurrencyConversion>
  loading: boolean
  error: string | null
  lastConversion: CurrencyConversion | null
}

export function useCurrency(): CurrencyHook {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [lastConversion, setLastConversion] = useState<CurrencyConversion | null>(null)

  const convertCurrency = async (
    from: string, 
    to: string, 
    amount: number, 
    country?: string
  ): Promise<CurrencyConversion> => {
    setLoading(true)
    setError(null)

    try {
      const params = new URLSearchParams({
        from: from.toUpperCase(),
        to: to.toUpperCase(),
        amount: amount.toString()
      })

      if (country) {
        params.append('country', country)
      }

      const response = await fetch(`/api/currency?${params.toString()}`)
      
      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to convert currency')
      }

      const data: CurrencyConversion = await response.json()
      setLastConversion(data)
      return data
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred'
      setError(errorMessage)
      throw err
    } finally {
      setLoading(false)
    }
  }

  const convertByCountry = async (
    from: string, 
    amount: number, 
    country: string
  ): Promise<CurrencyConversion> => {
    // Import the country to currency mapping to get the target currency
    const getCurrencyByCountry = (country: string): string => {
      const countryToCurrency: Record<string, string> = {
        'US': 'USD',
        'CA': 'CAD',
        'GB': 'GBP',
        'FR': 'EUR',
        'DE': 'EUR',
        'IT': 'EUR',
        'ES': 'EUR',
        'PT': 'EUR',
        'NL': 'EUR',
        'BE': 'EUR',
        'AT': 'EUR',
        'IE': 'EUR',
        'FI': 'EUR',
        'GR': 'EUR',
        'JP': 'JPY',
        'AU': 'AUD',
        'CH': 'CHF',
        'CN': 'CNY',
        'IN': 'INR',
        'BR': 'BRL',
        'MX': 'MXN',
        'TR': 'TRY',
        'ZA': 'ZAR',
        'RU': 'RUB',
        'KR': 'KRW',
        'SG': 'SGD',
        'TH': 'THB',
        'MY': 'MYR',
        'ID': 'IDR',
        'PH': 'PHP',
        'VN': 'VND',
        'AR': 'ARS',
        'CO': 'COP',
        'CL': 'CLP',
        'PE': 'PEN',
        'VE': 'VES',
        'EC': 'USD',
        'PY': 'PYG',
        'UY': 'UYU',
        'BO': 'BOB',
        'CR': 'CRC',
        'GT': 'GTQ',
        'SV': 'SVC',
        'HN': 'HNL',
        'NI': 'NIO',
        'PA': 'PAB',
        'JM': 'JMD',
        'TT': 'TTD',
        'BB': 'BBD',
        'BZ': 'BZD',
        'GD': 'XCD',
        'AG': 'XCD',
        'DM': 'XCD',
        'LC': 'XCD',
        'VC': 'XCD',
        'SR': 'SRD',
        'GF': 'EUR',
        'GY': 'GYD',
        'HT': 'HTG',
        'CU': 'CUP',
        'DO': 'DOP',
        'PR': 'USD',
        'BL': 'EUR',
        'MF': 'EUR',
        'GP': 'EUR',
        'MQ': 'EUR',
        'RE': 'EUR',
        'YT': 'EUR',
        'PM': 'EUR',
        'WF': 'XPF',
        'PF': 'XPF',
        'NC': 'XPF',
        'AS': 'USD',
        'GU': 'USD',
        'MP': 'USD',
        'VI': 'USD',
        'PW': 'USD',
        'FM': 'USD',
        'MH': 'USD',
        'MP': 'USD',
        'KI': 'AUD',
        'NR': 'AUD',
        'TV': 'AUD',
        'TO': 'TOP',
        'WS': 'WST',
        'FJ': 'FJD',
        'VU': 'VUV',
        'SB': 'SBD',
        'CK': 'NZD',
        'NU': 'NZD',
        'TK': 'NZD',
        'NF': 'AUD',
        'AU': 'AUD',
        'NZ': 'NZD',
        'PG': 'PGK',
        'ID': 'IDR',
        'MY': 'MYR',
        'SG': 'SGD',
        'BN': 'BND',
        'KH': 'KHR',
        'LA': 'LAK',
        'MM': 'MMK',
        'TH': 'THB',
        'PH': 'PHP',
        'VN': 'VND',
        'CN': 'CNY',
        'HK': 'HKD',
        'MO': 'MOP',
        'TW': 'TWD',
        'KP': 'KPW',
        'KR': 'KRW',
        'JP': 'JPY',
        'IN': 'INR',
        'LK': 'LKR',
        'NP': 'NPR',
        'BD': 'BDT',
        'BT': 'BTN',
        'PK': 'PKR',
        'AF': 'AFN',
        'TJ': 'TJS',
        'TM': 'TMT',
        'UZ': 'UZS',
        'KZ': 'KZT',
        'KG': 'KGS',
        'AZ': 'AZN',
        'GE': 'GEL',
        'AM': 'AMD',
        'IR': 'IRR',
        'IQ': 'IQD',
        'SY': 'SYP',
        'LB': 'LBP',
        'JO': 'JOD',
        'IL': 'ILS',
        'PS': 'ILS',
        'SA': 'SAR',
        'YE': 'YER',
        'OM': 'OMR',
        'AE': 'AED',
        'QA': 'QAR',
        'BH': 'BHD',
        'KW': 'KWD',
        'EG': 'EGP',
        'SD': 'SDG',
        'ER': 'ERN',
        'DJ': 'DJF',
        'ET': 'ETB',
        'SO': 'SOS',
        'KE': 'KES',
        'UG': 'UGX',
        'TZ': 'TZS',
        'RW': 'RWF',
        'BI': 'BIF',
        'CD': 'CDF',
        'AO': 'AOA',
        'GA': 'XAF',
        'CM': 'XAF',
        'CF': 'XAF',
        'TD': 'XAF',
        'GQ': 'XAF',
        'CG': 'XAF',
        'SN': 'XOF',
        'CI': 'XOF',
        'BF': 'XOF',
        'ML': 'XOF',
        'NE': 'XOF',
        'BJ': 'XOF',
        'TG': 'XOF',
        'GW': 'XOF',
        'MR': 'MRO',
        'GM': 'GMD',
        'GN': 'GNF',
        'SL': 'SLL',
        'LR': 'LRD',
        'GH': 'GHS',
        'NG': 'NGN',
        'CM': 'XAF',
        'SN': 'XOF',
        'ZA': 'ZAR',
        'BW': 'BWP',
        'NA': 'NAD',
        'SZ': 'SZL',
        'LS': 'LSL',
        'MW': 'MWK',
        'ZM': 'ZMW',
        'Zimbabwe': 'USD',
        'Mozambique': 'MZN',
        'Botswana': 'BWP',
        'Namibia': 'NAD',
        'Angola': 'AOA',
        'Malawi': 'MWK',
        'Zambia': 'ZMW',
        'Zimbabwe': 'USD',
        'Comoros': 'KMF',
        'Seychelles': 'SCR',
        'Mauritius': 'MUR',
        'Madagascar': 'MGA',
        'Cape Verde': 'CVE',
        'Sao Tome': 'STN',
        'Equatorial Guinea': 'XAF',
        'Gabon': 'XAF',
        'Congo': 'XAF',
        'DRC': 'CDF',
        'Burundi': 'BIF',
        'Rwanda': 'RWF',
        'Uganda': 'UGX',
        'Kenya': 'KES',
        'Tanzania': 'TZS',
        'Mozambique': 'MZN',
        'Zambia': 'ZMW',
        'Zimbabwe': 'USD'
      }
      
      const targetCurrency = countryToCurrency[country] || 'USD'
      return targetCurrency
    }
    
    const targetCurrency = getCurrencyByCountry(country)
    return convertCurrency(from, targetCurrency, amount, country)
  }

  return {
    convertCurrency,
    convertByCountry,
    loading,
    error,
    lastConversion
  }
}

// Format currency with symbol
export function formatCurrency(amount: number, currency: string): string {
  const currencySymbols: Record<string, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    JPY: '¥',
    CAD: 'C$',
    AUD: 'A$',
    CHF: 'CHF',
    CNY: '¥',
    INR: '₹',
    BRL: 'R$',
    MXN: '$',
    RUB: '₽',
    KRW: '₩',
    SGD: 'S$',
    HKD: 'HK$',
    SEK: 'kr',
    NOK: 'kr',
    DKK: 'kr',
    PLN: 'zł',
    THB: '฿',
    MYR: 'RM',
    IDR: 'Rp',
    PHP: '₱',
    VND: '₫',
    ZAR: 'R',
    TRY: '₺',
    ILS: '₪',
    AED: 'د.إ',
    SAR: '﷼',
    QAR: '﷼',
    KWD: 'د.ك',
    BHD: 'د.ب',
    OMR: 'ر.ع.',
    JOD: 'د.أ',
    LBP: 'ل.ل',
    EGP: 'ج.م',
    MAD: 'د.م.',
    TND: 'د.ت',
    DZD: 'د.ج',
    NGN: '₦',
    KES: 'KSh',
    GHS: '₵',
    XAF: 'FCFA',
    XOF: 'CFA',
    XPF: 'CFPF',
    CLP: '$',
    ARS: '$',
    COP: '$',
    PEN: 'S/',
    UYU: '$',
    PYG: '₲',
    BOB: 'Bs.',
    CRC: '₡',
    GTQ: 'Q',
    SVC: '$',
    HNL: 'L',
    NIO: 'C$',
    CUP: '$',
    DOP: 'RD$',
    HTG: 'G',
    JMD: 'J$',
    TTD: 'TT$',
    BBD: 'Bds$',
    BZD: 'BZ$',
    XCD: 'EC$',
    BSD: 'B$',
    BMD: 'BD$',
    SBD: 'SI$',
    FJD: 'FJ$',
    WST: 'WS$',
    PGK: 'K',
    VUV: 'VT',
    SLL: 'Le',
    LRD: 'L$',
    GMD: 'D',
    MRO: 'UM',
    MGA: 'Ar',
    DJF: 'Fdj',
    ERN: 'Nfk',
    ETB: 'Br',
    SDG: 'ج.س.',
    GNF: 'FG',
    BIF: 'FBu',
    RWF: 'RF',
    CDF: 'FC',
    AOA: 'Kz',
    KZT: '₸',
    KGS: 'с',
    UZS: 'сўм',
    TJS: 'SM',
    TMT: 'm',
    GEL: '₾',
    AMD: '֏',
    AZN: '₼',
    BYN: 'Br',
    MDL: 'L',
    RON: 'lei',
    BGN: 'лв',
    HRK: 'kn',
    CZK: 'Kč',
    HUF: 'Ft',
    PZL: 'zł',
    UAH: '₴',
    MKD: 'ден',
    ALL: 'L',
    BAM: 'KM'
  }

  const symbol = currencySymbols[currency] || currency
  return `${symbol}${amount.toLocaleString()}`
}

// Get currency symbol
export function getCurrencySymbol(currency: string): string {
  const currencySymbols: Record<string, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    JPY: '¥',
    CAD: 'C$',
    AUD: 'A$',
    CHF: 'CHF',
    CNY: '¥',
    INR: '₹',
    BRL: 'R$',
    MXN: '$',
    RUB: '₽',
    KRW: '₩',
    SGD: 'S$',
    HKD: 'HK$',
    SEK: 'kr',
    NOK: 'kr',
    DKK: 'kr',
    PLN: 'zł',
    THB: '฿',
    MYR: 'RM',
    IDR: 'Rp',
    PHP: '₱',
    VND: '₫',
    ZAR: 'R',
    TRY: '₺',
    ILS: '₪',
    AED: 'د.إ',
    SAR: '﷼',
    QAR: '﷼',
    KWD: 'د.ك',
    BHD: 'د.ب',
    OMR: 'ر.ع.',
    JOD: 'د.أ',
    LBP: 'ل.ل',
    EGP: 'ج.م',
    MAD: 'د.م.',
    TND: 'د.ت',
    DZD: 'د.ج',
    NGN: '₦',
    KES: 'KSh',
    GHS: '₵',
    XAF: 'FCFA',
    XOF: 'CFA',
    XPF: 'CFPF',
    CLP: '$',
    ARS: '$',
    COP: '$',
    PEN: 'S/',
    UYU: '$',
    PYG: '₲',
    BOB: 'Bs.',
    CRC: '₡',
    GTQ: 'Q',
    SVC: '$',
    HNL: 'L',
    NIO: 'C$',
    CUP: '$',
    DOP: 'RD$',
    HTG: 'G',
    JMD: 'J$',
    TTD: 'TT$',
    BBD: 'Bds$',
    BZD: 'BZ$',
    XCD: 'EC$',
    BSD: 'B$',
    BMD: 'BD$',
    SBD: 'SI$',
    FJD: 'FJ$',
    WST: 'WS$',
    PGK: 'K',
    VUV: 'VT',
    SLL: 'Le',
    LRD: 'L$',
    GMD: 'D',
    MRO: 'UM',
    MGA: 'Ar',
    DJF: 'Fdj',
    ERN: 'Nfk',
    ETB: 'Br',
    SDG: 'ج.س.',
    GNF: 'FG',
    BIF: 'FBu',
    RWF: 'RF',
    CDF: 'FC',
    AOA: 'Kz',
    KZT: '₸',
    KGS: 'с',
    UZS: 'сўм',
    TJS: 'SM',
    TMT: 'm',
    GEL: '₾',
    AMD: '֏',
    AZN: '₼',
    BYN: 'Br',
    MDL: 'L',
    RON: 'lei',
    BGN: 'лв',
    HRK: 'kn',
    CZK: 'Kč',
    HUF: 'Ft',
    PZL: 'zł',
    UAH: '₴',
    MKD: 'ден',
    ALL: 'L',
    BAM: 'KM'
  }

  return currencySymbols[currency] || currency
}

// Country to currency mapping
export function getCurrencyByCountry(country: string): string {
  const countryToCurrency: Record<string, string> = {
    'US': 'USD',
    'CA': 'CAD',
    'GB': 'GBP',
    'FR': 'EUR',
    'DE': 'EUR',
    'IT': 'EUR',
    'ES': 'EUR',
    'PT': 'EUR',
    'NL': 'EUR',
    'BE': 'EUR',
    'AT': 'EUR',
    'IE': 'EUR',
    'FI': 'EUR',
    'GR': 'EUR',
    'CY': 'EUR',
    'MT': 'EUR',
    'SK': 'EUR',
    'SI': 'EUR',
    'LV': 'EUR',
    'EE': 'EUR',
    'LT': 'EUR',
    'LU': 'EUR',
    'JP': 'JPY',
    'AU': 'AUD',
    'CH': 'CHF',
    'CN': 'CNY',
    'IN': 'INR',
    'BR': 'BRL',
    'MX': 'MXN',
    'RU': 'RUB',
    'KR': 'KRW',
    'SG': 'SGD',
    'HK': 'HKD',
    'SE': 'SEK',
    'NO': 'NOK',
    'DK': 'DKK',
    'PL': 'PLN',
    'TH': 'THB',
    'MY': 'MYR',
    'ID': 'IDR',
    'PH': 'PHP',
    'VN': 'VND',
    'ZA': 'ZAR',
    'TR': 'TRY',
    'IL': 'ILS',
    'AE': 'AED',
    'SA': 'SAR',
    'QA': 'QAR',
    'KW': 'KWD',
    'BH': 'BHD',
    'OM': 'OM',
    'JO': 'JOD',
    'LB': 'LBP',
    'EG': 'EGP',
    'MA': 'MAD',
    'TN': 'TND',
    'DZ': 'DZD',
    'NG': 'NGN',
    'KE': 'KES',
    'GH': 'GHS',
    'CM': 'XAF',
    'SN': 'XOF',
    'PF': 'XPF',
    'CL': 'CLP',
    'AR': 'ARS',
    'CO': 'COP',
    'PE': 'PEN',
    'UY': 'UYU',
    'PY': 'PYG',
    'BO': 'BOB',
    'CR': 'CRC',
    'GT': 'GTQ',
    'SV': 'SVC',
    'HN': 'HNL',
    'NI': 'NIO',
    'CU': 'CUP',
    'DO': 'DOP',
    'HT': 'HTG',
    'JM': 'JMD',
    'TT': 'TTD',
    'BB': 'BBD',
    'BZ': 'BZD',
    'AG': 'XCD',
    'BS': 'BSD',
    'BM': 'BMD',
    'SB': 'SBD',
    'FJ': 'FJD',
    'WS': 'WST',
    'PG': 'PGK',
    'VU': 'VUV',
    'SL': 'SLL',
    'LR': 'LRD',
    'GM': 'GMD',
    'MR': 'MRO',
    'MG': 'MGA',
    'DJ': 'DJF',
    'ER': 'ERN',
    'ET': 'ETB',
    'SD': 'SDG',
    'GN': 'GNF',
    'BI': 'BIF',
    'RW': 'RWF',
    'CD': 'CDF',
    'AO': 'AOA',
    'KZ': 'KZT',
    'KG': 'KG',
    'UZ': 'UZS',
    'TJ': 'TJS',
    'TM': 'TMT',
    'GE': 'GEL',
    'AM': 'AMD',
    'AZ': 'AZN',
    'BY': 'BYN',
    'MD': 'MDL',
    'RO': 'RON',
    'BG': 'BGN',
    'HR': 'HRK',
    'CZ': 'CZK',
    'HU': 'HUF',
    'UA': 'UAH',
    'MK': 'MKD',
    'AL': 'ALL',
    'BA': 'BAM'
  }

  return countryToCurrency[country] || 'USD'
}